//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd", IsNullable=false)]
public partial class ProcessOrders {
    
    private ProcessOrdersShipment[] shipmentsField;
    
    private ProcessOrdersCancellation[] cancellationsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Shipment", IsNullable=false)]
    public ProcessOrdersShipment[] Shipments {
        get {
            return this.shipmentsField;
        }
        set {
            this.shipmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Cancellation", IsNullable=false)]
    public ProcessOrdersCancellation[] Cancellations {
        get {
            return this.cancellationsField;
        }
        set {
            this.cancellationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class ProcessOrdersShipment {
    
    private long orderIdField;

    private System.DateTime? dateExpectedDelivery;

    private System.DateTime dateTimeField;
    
    private ProcessOrdersShipmentTransporter transporterField;

    private long[] orderItemsField;
    
    /// <remarks/>
    public long OrderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }

    /// <remarks/>
    public System.DateTime? DateExpectedDelivery
    {
        get
        {
            return this.dateExpectedDelivery;
        }
        set
        {
            this.dateExpectedDelivery = value;
        }
    }

    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <remarks/>
    public ProcessOrdersShipmentTransporter Transporter {
        get {
            return this.transporterField;
        }
        set {
            this.transporterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable=false)]
    public long[] OrderItems
    {
        get {
            return this.orderItemsField;
        }
        set {
            this.orderItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class ProcessOrdersShipmentTransporter {
    
    private string codeField;
    
    private string trackAndTraceCodeField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string TrackAndTraceCode {
        get {
            return this.trackAndTraceCodeField;
        }
        set {
            this.trackAndTraceCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class AddressDetails {
    
    private string salutationCodeField;
    
    private string firstNameField;
    
    private string surnameField;
    
    private string streetnameField;
    
    private long housenumberField;
    
    private string housenumberExtendedField;
    
    private string addressSupplementField;
    
    private string zipCodeField;
    
    private string cityField;
    
    private string countryCodeField;
    
    private string emailField;
    
    private string telephoneField;
    
    private string companyField;
    
    /// <remarks/>
    public string SalutationCode {
        get {
            return this.salutationCodeField;
        }
        set {
            this.salutationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Streetname {
        get {
            return this.streetnameField;
        }
        set {
            this.streetnameField = value;
        }
    }
    
    /// <remarks/>
    public long Housenumber {
        get {
            return this.housenumberField;
        }
        set {
            this.housenumberField = value;
        }
    }
    
    /// <remarks/>
    public string HousenumberExtended {
        get {
            return this.housenumberExtendedField;
        }
        set {
            this.housenumberExtendedField = value;
        }
    }
    
    /// <remarks/>
    public string AddressSupplement {
        get {
            return this.addressSupplementField;
        }
        set {
            this.addressSupplementField = value;
        }
    }
    
    /// <remarks/>
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class ProcessOrdersCancellation {
    
    private long orderIdField;
    
    private System.DateTime dateTimeField;
    
    private ProcessOrdersCancellationReasonCode reasonCodeField;
    
    private long[] orderItemsField;
    
    /// <remarks/>
    public long OrderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <remarks/>
    public ProcessOrdersCancellationReasonCode ReasonCode {
        get {
            return this.reasonCodeField;
        }
        set {
            this.reasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable=false)]
    public long[] OrderItems {
        get {
            return this.orderItemsField;
        }
        set {
            this.orderItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public enum ProcessOrdersCancellationReasonCode {
    
    /// <remarks/>
    OUT_OF_STOCK,
    
    /// <remarks/>
    REQUESTED_BY_CUSTOMER,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd", IsNullable=false)]
public partial class ProcessOrdersResult {
    
    private long processOrderIdField;
    
    /// <remarks/>
    public long ProcessOrderId {
        get {
            return this.processOrderIdField;
        }
        set {
            this.processOrderIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd", IsNullable=false)]
public partial class ProcessOrdersOverview {
    
    private long processOrderIdField;
    
    private Status statusField;
    
    private ProcessOrdersOverviewOrder[] orderField;
    
    /// <remarks/>
    public long ProcessOrderId {
        get {
            return this.processOrderIdField;
        }
        set {
            this.processOrderIdField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Order")]
    public ProcessOrdersOverviewOrder[] Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public enum Status {
    
    /// <remarks/>
    RECEIVED,
    
    /// <remarks/>
    PENDING,
    
    /// <remarks/>
    SUCCESS,
    
    /// <remarks/>
    ERROR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class ProcessOrdersOverviewOrder {
    
    private long orderIdField;
    
    private Status statusField;
    
    private System.DateTime dateTimeField;
    
    private ProcessOrdersOverviewOrderOrderItemData[] orderItemListField;
    
    /// <remarks/>
    public long OrderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("OrderItemData", IsNullable=false)]
    public ProcessOrdersOverviewOrderOrderItemData[] OrderItemList {
        get {
            return this.orderItemListField;
        }
        set {
            this.orderItemListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class ProcessOrdersOverviewOrderOrderItemData {
    
    private long orderItemIdField;
    
    private Process processField;
    
    private Status statusField;
    
    private string errorMessageField;
    
    /// <remarks/>
    public long OrderItemId {
        get {
            return this.orderItemIdField;
        }
        set {
            this.orderItemIdField = value;
        }
    }
    
    /// <remarks/>
    public Process Process {
        get {
            return this.processField;
        }
        set {
            this.processField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public enum Process {
    
    /// <remarks/>
    SHIP,
    
    /// <remarks/>
    CANCEL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd", IsNullable=false)]
public partial class Payments {
    
    private PaymentsPayment[] paymentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Payment")]
    public PaymentsPayment[] Payment {
        get {
            return this.paymentField;
        }
        set {
            this.paymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class PaymentsPayment {
    
    private long creditInvoiceNumberField;
    
    private System.DateTime dateTimePaymentField;
    
    private decimal paymentAmountField;
    
    private PaymentsPaymentPaymentShipment[] paymentShipmentsField;
    
    /// <remarks/>
    public long CreditInvoiceNumber {
        get {
            return this.creditInvoiceNumberField;
        }
        set {
            this.creditInvoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimePayment {
        get {
            return this.dateTimePaymentField;
        }
        set {
            this.dateTimePaymentField = value;
        }
    }
    
    /// <remarks/>
    public decimal PaymentAmount {
        get {
            return this.paymentAmountField;
        }
        set {
            this.paymentAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PaymentShipment", IsNullable=false)]
    public PaymentsPaymentPaymentShipment[] PaymentShipments {
        get {
            return this.paymentShipmentsField;
        }
        set {
            this.paymentShipmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class PaymentsPaymentPaymentShipment {
    
    private long packageSlipNumberField;
    
    private long orderIdField;
    
    private decimal paymentShipmentAmountField;
    
    private PaymentsPaymentPaymentShipmentPaymentStatus paymentStatusField;
    
    private System.DateTime dateTimeShipmentField;
    
    private PaymentsPaymentPaymentShipmentPaymentShipmentItem[] paymentShipmentItemsField;
    
    /// <remarks/>
    public long PackageSlipNumber {
        get {
            return this.packageSlipNumberField;
        }
        set {
            this.packageSlipNumberField = value;
        }
    }
    
    /// <remarks/>
    public long OrderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }
    
    /// <remarks/>
    public decimal PaymentShipmentAmount {
        get {
            return this.paymentShipmentAmountField;
        }
        set {
            this.paymentShipmentAmountField = value;
        }
    }
    
    /// <remarks/>
    public PaymentsPaymentPaymentShipmentPaymentStatus PaymentStatus {
        get {
            return this.paymentStatusField;
        }
        set {
            this.paymentStatusField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimeShipment {
        get {
            return this.dateTimeShipmentField;
        }
        set {
            this.dateTimeShipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PaymentShipmentItem", IsNullable=false)]
    public PaymentsPaymentPaymentShipmentPaymentShipmentItem[] PaymentShipmentItems {
        get {
            return this.paymentShipmentItemsField;
        }
        set {
            this.paymentShipmentItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public enum PaymentsPaymentPaymentShipmentPaymentStatus {
    
    /// <remarks/>
    FINAL,
    
    /// <remarks/>
    CONTINUATION,
    
    /// <remarks/>
    GUARANTEE,
    
    /// <remarks/>
    BACK_PAYMENT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class PaymentsPaymentPaymentShipmentPaymentShipmentItem {
    
    private long orderItemIdField;
    
    private string eANField;
    
    private string referenceCodeField;
    
    private long quantityField;
    
    private decimal priceField;
    
    private decimal shippingContributionField;
    
    private decimal transactionFeeField;
    
    private decimal totalAmountField;
    
    private PaymentsPaymentPaymentShipmentPaymentShipmentItemShipmentStatus shipmentStatusField;
    
    /// <remarks/>
    public long OrderItemId {
        get {
            return this.orderItemIdField;
        }
        set {
            this.orderItemIdField = value;
        }
    }
    
    /// <remarks/>
    public string EAN {
        get {
            return this.eANField;
        }
        set {
            this.eANField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceCode {
        get {
            return this.referenceCodeField;
        }
        set {
            this.referenceCodeField = value;
        }
    }
    
    /// <remarks/>
    public long Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public decimal ShippingContribution {
        get {
            return this.shippingContributionField;
        }
        set {
            this.shippingContributionField = value;
        }
    }
    
    /// <remarks/>
    public decimal TransactionFee {
        get {
            return this.transactionFeeField;
        }
        set {
            this.transactionFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalAmount {
        get {
            return this.totalAmountField;
        }
        set {
            this.totalAmountField = value;
        }
    }
    
    /// <remarks/>
    public PaymentsPaymentPaymentShipmentPaymentShipmentItemShipmentStatus ShipmentStatus {
        get {
            return this.shipmentStatusField;
        }
        set {
            this.shipmentStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public enum PaymentsPaymentPaymentShipmentPaymentShipmentItemShipmentStatus {
    
    /// <remarks/>
    NORMAL,
    
    /// <remarks/>
    RETURN,
    
    /// <remarks/>
    LIM,
    
    /// <remarks/>
    RETURNLIM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd", IsNullable=false)]
public partial class OpenOrders {
    
    private OpenOrdersOpenOrder[] openOrderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OpenOrder")]
    public OpenOrdersOpenOrder[] OpenOrder {
        get {
            return this.openOrderField;
        }
        set {
            this.openOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class OpenOrdersOpenOrder {
    
    private long orderIdField;
    
    private System.DateTime dateTimeCustomerField;
    
    private System.DateTime dateTimeDropShipperField;
    
    private bool paidField;
    
    private OpenOrdersOpenOrderBuyer buyerField;
    
    private OpenOrdersOpenOrderOpenOrderItem[] openOrderItemsField;
    
    /// <remarks/>
    public long OrderId {
        get {
            return this.orderIdField;
        }
        set {
            this.orderIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimeCustomer {
        get {
            return this.dateTimeCustomerField;
        }
        set {
            this.dateTimeCustomerField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimeDropShipper {
        get {
            return this.dateTimeDropShipperField;
        }
        set {
            this.dateTimeDropShipperField = value;
        }
    }
    
    /// <remarks/>
    public bool Paid {
        get {
            return this.paidField;
        }
        set {
            this.paidField = value;
        }
    }
    
    /// <remarks/>
    public OpenOrdersOpenOrderBuyer Buyer {
        get {
            return this.buyerField;
        }
        set {
            this.buyerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("OpenOrderItem", IsNullable=false)]
    public OpenOrdersOpenOrderOpenOrderItem[] OpenOrderItems {
        get {
            return this.openOrderItemsField;
        }
        set {
            this.openOrderItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class OpenOrdersOpenOrderBuyer {
    
    private AddressDetails shipmentDetailsField;
    
    private AddressDetails billingDetailsField;
    
    /// <remarks/>
    public AddressDetails ShipmentDetails {
        get {
            return this.shipmentDetailsField;
        }
        set {
            this.shipmentDetailsField = value;
        }
    }
    
    /// <remarks/>
    public AddressDetails BillingDetails {
        get {
            return this.billingDetailsField;
        }
        set {
            this.billingDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://plazaapi.bol.com/services/xsd/plazaapiservice-1.0.xsd")]
public partial class OpenOrdersOpenOrderOpenOrderItem {
    
    private long orderItemIdField;
    
    private string eANField;
    
    private string referenceCodeField;
    
    private string titleField;
    
    private long quantityField;
    
    private decimal priceField;
    
    private string deliveryPeriodField;
    
    private decimal transactionFeeField;
    
    /// <remarks/>
    public long OrderItemId {
        get {
            return this.orderItemIdField;
        }
        set {
            this.orderItemIdField = value;
        }
    }
    
    /// <remarks/>
    public string EAN {
        get {
            return this.eANField;
        }
        set {
            this.eANField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceCode {
        get {
            return this.referenceCodeField;
        }
        set {
            this.referenceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public long Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryPeriod {
        get {
            return this.deliveryPeriodField;
        }
        set {
            this.deliveryPeriodField = value;
        }
    }
    
    /// <remarks/>
    public decimal TransactionFee {
        get {
            return this.transactionFeeField;
        }
        set {
            this.transactionFeeField = value;
        }
    }
}
